on:
  push:
    paths:
      - .github/workflows/gather-data.yml

env:
  ORGANIZATION: devops-actions

jobs:
  gather-data:
    runs-on: ubuntu-latest
    steps:
      - uses: devops-actions/load-used-actions@v1.3.4
        id: load-used-actions
        with:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ env.ORGANIZATION }}

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: used-actions
          path: ${{ steps.load-used-actions.outputs.actions-file }}

      - uses: devops-actions/devops-actions/load-available-actions@v2.1.14
        with: 
          PAT: ${{ secrets.PAT }} 
          organization: ${{ env.ORGANIZATION }}
        id: load-available-actions

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: available-actions
          path: ${{ steps.load-available-actions.outputs.actions-file-path }}
