name: Process data
on:
  push:
    paths:
      - .github/workflows/process-data.yml
      - .github/workflows/script.ps1

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      -  name: Download last used-actions
         uses: blablacar/action-download-last-artifact@v0.1.0
         with:
           name: used-actions
      
      -  name: Download last available-actions
         uses: blablacar/action-download-last-artifact@v0.1.0
         with:
           name: available-actions

      - run: |
          ls -la

      - uses: actions/checkout@v3

      - shell: pwsh
        run: |
          $pwd
          ls -la
          . /github/workflows/script.ps1


