name: Process data
on:
  push:
    paths:
      - .github/workflows/process-data.yml
      - .github/workflows/script.ps1

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      # get the code to run the pwsh script
      - uses: actions/checkout@v3

      - name: Download last used-actions
        uses: blablacar/action-download-last-artifact@v0.1.0
        with:
          name: used-actions
      
      - name: Download last available-actions
        uses: blablacar/action-download-last-artifact@v0.1.0
        with:
          name: available-actions

      - run: |
          $pwd
          ls -la

      - shell: pwsh
        run: |
          $pwd
          ls -la

          Write-Host "GITHUB_WORKSPACE: [$($env:GITHUB_WORKSPACE)]"
          . .github/workflows/script.ps1

          main -availableActionsFile "actions.json" -usedActionsFile "used-actions.json"


