name: Process data
on:
  push:
    paths:
      - .github/workflows/process-data.yml

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      -  name: Download last used-actions
         uses: blablacar/action-download-last-artifact@v0.1.0
         with:
           name: used-actions
      
      -  name: Download last available-actions
         uses: blablacar/action-download-last-artifact@v0.1.0
         with:
           name: available-actions

      - run: |
          ls -la

      - shell: pwsh
        run: |
          $availableActions = Get-Content "actions.json" | ConvertFrom-Json
          Write-Host "Found [$($availableActions.actions.Length)] available actions"
          Write-Host "Found [$($availableActions.workflows.Length)] available reusable workflows"

          $usedActions = Get-Content "used-actions.json" | ConvertFrom-Json
          Write-Host "Used actions: $($usedActions | ConvertTo-Json)"
          Write-Host "Found [$($usedActions.actions.Length)] available actions"
          Write-Host "Found [$($usedActions.workflows.Length)] available reusable workflows"
